CAMERA_RESOLUTION = (320, 240)
CAMERA_TARGET_FPS = 60
CAMERA_EXPOSURE_TIME = 20000     # µs, fallback if AE metadata read fails
CAMERA_ANALOGUE_GAIN = 2.0
CAMERA_INDEX = 0

LOG_EPSILON = 1e-3

DVS_CONTRAST_THRESHOLD = 0.30   # log-units; raise for fewer/cleaner events
NOISE_FILTER_ENABLED = True
NOISE_MIN_NEIGHBOURS = 1

EVENT_BUFFER_CAPACITY = 500_000

VISUALIZATION_ENABLED = True
VIZ_ACCUMULATION_WINDOW_MS = 10
VIZ_WINDOW_NAME = "DVS Event Frame"

PERF_REPORT_INTERVAL_SEC = 2.0
CPU_AFFINITY_CORES = [0, 1]
